<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { RefreshRight, Search } from '@element-plus/icons-vue'
import PageHeader from '@/components/PageHeader.vue'
import ContentStatus from '@/components/ContentStatus.vue'
import { getOperationLogs, getPublishLogs } from '@/api/logs'
import { CONTENT_TYPES, PUBLISH_RECORD_STATUS } from '@/constants'
import { formatDate } from '@/utils/format'
import type { ContentType } from '@/types/content'
import type { OperationLog, OperationLogQuery, PublishLog, PublishLogQuery, PublishRecordStatus } from '@/types/publish'

const activeTab = ref('operations'); const operationLoading = ref(false); const publishLoading = ref(false); const operationItems = ref<OperationLog[]>([]); const publishItems = ref<PublishLog[]>([]); const operationTotal = ref(0); const publishTotal = ref(0); const operationRange = ref<[string, string]>(); const publishRange = ref<[string, string]>()
const operationQuery = reactive<OperationLogQuery>({ page: 1, page_size: 10, action: '' }); const publishQuery = reactive<PublishLogQuery>({ page: 1, page_size: 10, keyword: '', content_type: '', status: '' })
const publishLogStatuses = Object.entries(PUBLISH_RECORD_STATUS)
const actions = ['登录', '新建内容', '编辑内容', '删除内容', '提交审核', '审核通过', '审核驳回', '发布内容', '重新发布', '新增用户', '编辑用户', '启用用户', '禁用用户', '删除用户', '新增部门', '编辑部门', '启用部门', '禁用部门', '删除部门', '新增分类', '编辑分类', '启用分类', '禁用分类', '删除分类', '新增发布配置', '编辑发布配置', '启用发布配置', '禁用发布配置', '测试发布配置', '删除发布配置']
async function loadOperations() { operationLoading.value = true; operationQuery.date_from = operationRange.value?.[0]; operationQuery.date_to = operationRange.value?.[1]; try { const result = await getOperationLogs(operationQuery); operationItems.value = result.items; operationTotal.value = result.total } catch (e) { ElMessage.error(e instanceof Error ? e.message : '操作日志加载失败') } finally { operationLoading.value = false } }
async function loadPublishes() { publishLoading.value = true; publishQuery.date_from = publishRange.value?.[0]; publishQuery.date_to = publishRange.value?.[1]; try { const result = await getPublishLogs(publishQuery); publishItems.value = result.items; publishTotal.value = result.total } catch (e) { ElMessage.error(e instanceof Error ? e.message : '发布日志加载失败') } finally { publishLoading.value = false } }
function resetOperations() { Object.assign(operationQuery, { page: 1, action: '', user_id: undefined }); operationRange.value = undefined; loadOperations() }
function resetPublishes() { Object.assign(publishQuery, { page: 1, keyword: '', content_type: '', status: '' }); publishRange.value = undefined; loadPublishes() }
onMounted(() => { loadOperations(); loadPublishes() })
</script>
<template>
  <div class="page-shell">
    <PageHeader title="系统日志" description="查看关键后台操作与每一次发布结果。日志记录只读。" eyebrow="AUDIT & DELIVERY LOG" />
    <section class="paper-card log-card"><el-tabs v-model="activeTab">
      <el-tab-pane label="操作日志" name="operations"><div class="tab-description"><div><strong>操作日志</strong><span>登录、内容、审核、用户、部门与发布配置变更</span></div></div><div class="tab-filter"><el-select v-model="operationQuery.action" clearable placeholder="全部操作类型" style="width:180px"><el-option v-for="action in actions" :key="action" :label="action" :value="action" /></el-select><el-date-picker v-model="operationRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" /><el-button type="primary" :icon="Search" @click="operationQuery.page = 1; loadOperations()">查询</el-button><el-button :icon="RefreshRight" @click="resetOperations">重置</el-button></div><el-table v-loading="operationLoading" :data="operationItems"><el-table-column label="时间" width="170"><template #default="scope">{{ formatDate(scope.row.created_at) }}</template></el-table-column><el-table-column prop="user_name" label="用户" width="130" /><el-table-column prop="action" label="操作" width="150"><template #default="scope"><el-tag effect="plain" type="info">{{ scope.row.action }}</el-tag></template></el-table-column><el-table-column prop="object" label="对象" min-width="150" /><el-table-column prop="description" label="说明" min-width="260" /></el-table><div class="pagination-wrap"><el-pagination v-model:current-page="operationQuery.page" v-model:page-size="operationQuery.page_size" :total="operationTotal" layout="total, sizes, prev, pager, next" @change="loadOperations" /></div></el-tab-pane>
      <el-tab-pane label="发布日志" name="publishes"><div class="tab-description"><div><strong>发布日志</strong><span>发布目标、处理结果、访问 URL 与失败原因</span></div></div><div class="tab-filter"><el-input v-model="publishQuery.keyword" clearable placeholder="内容标题" style="width:190px" /><el-select v-model="publishQuery.content_type" clearable placeholder="全部内容类型" style="width:155px"><el-option v-for="(label, value) in CONTENT_TYPES" :key="value" :label="label" :value="value as ContentType" /></el-select><el-select v-model="publishQuery.status" clearable placeholder="全部状态" style="width:130px"><el-option v-for="[value, label] in publishLogStatuses" :key="value" :label="label" :value="value as PublishRecordStatus" /></el-select><el-date-picker v-model="publishRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期" /><el-button type="primary" :icon="Search" @click="publishQuery.page = 1; loadPublishes()">查询</el-button><el-button :icon="RefreshRight" @click="resetPublishes">重置</el-button></div><el-table v-loading="publishLoading" :data="publishItems"><el-table-column label="时间" width="165"><template #default="scope">{{ formatDate(scope.row.created_at) }}</template></el-table-column><el-table-column prop="content_title" label="内容" min-width="190" /><el-table-column prop="target_name" label="发布目标" width="130" /><el-table-column label="发布结果" width="100"><template #default="scope"><ContentStatus kind="publish-record" :status="scope.row.status" /></template></el-table-column><el-table-column label="访问 URL" min-width="220"><template #default="scope"><a v-if="scope.row.view_url" :href="scope.row.view_url" target="_blank" rel="noopener noreferrer" class="log-url mono">{{ scope.row.view_url }}</a><span v-else>—</span></template></el-table-column><el-table-column label="失败原因" min-width="200"><template #default="scope"><el-tooltip v-if="scope.row.failure_reason" :content="scope.row.failure_reason" placement="top"><span class="failure-reason">{{ scope.row.failure_reason }}</span></el-tooltip><span v-else>—</span></template></el-table-column></el-table><div class="pagination-wrap"><el-pagination v-model:current-page="publishQuery.page" v-model:page-size="publishQuery.page_size" :total="publishTotal" layout="total, sizes, prev, pager, next" @change="loadPublishes" /></div></el-tab-pane>
    </el-tabs></section>
  </div>
</template>
<style scoped>
.log-card { padding: 4px 20px 18px; }.log-card :deep(.el-tabs__header) { margin-bottom: 0; }.tab-description { min-height: 70px; display: flex; align-items: center; justify-content: space-between; }.tab-description div { display: flex; flex-direction: column; gap: 5px; }.tab-description strong { font-size: 14px; }.tab-description span { color: #8c95a4; font-size: 11px; }.tab-filter { display: flex; gap: 9px; padding: 13px 14px; margin-bottom: 14px; background: #f7f8fa; border: 1px solid #e6e9ee; }.log-url { display: block; overflow: hidden; color: var(--blue); font-size: 10px; text-overflow: ellipsis; white-space: nowrap; }.failure-reason { display: block; max-width: 230px; overflow: hidden; color: var(--danger); text-overflow: ellipsis; white-space: nowrap; }
</style>
