<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import { RefreshRight, Search } from '@element-plus/icons-vue'
import PageHeader from '@/components/PageHeader.vue'
import ContentStatus from '@/components/ContentStatus.vue'
import { getOperationLogs, getPublishLogs } from '@/api/logs'
import { getRequestErrorMessage } from '@/api/request'
import { CONTENT_TYPES, OPERATION_ACTIONS, PUBLISH_RECORD_STATUS } from '@/constants'
import { formatDate } from '@/utils/format'
import type { ContentType } from '@/types/content'
import type { OperationLog, OperationLogQuery, PublishLog, PublishLogQuery, PublishRecordStatus } from '@/types/publish'

const activeTab = ref('operations'); const operationLoading = ref(false); const publishLoading = ref(false); const operationItems = ref<OperationLog[]>([]); const publishItems = ref<PublishLog[]>([]); const operationTotal = ref(0); const publishTotal = ref(0); const operationRange = ref<[string, string]>(); const publishRange = ref<[string, string]>()
const { t } = useI18n()
const operationQuery = reactive<OperationLogQuery>({ page: 1, page_size: 10, action: '' }); const publishQuery = reactive<PublishLogQuery>({ page: 1, page_size: 10, keyword: '', content_type: '', status: '' })
const publishLogStatuses = Object.entries(PUBLISH_RECORD_STATUS)
const actions = computed(() => Object.entries(OPERATION_ACTIONS).map(([value, key]) => ({ value, label: t(key) })))
const operationLabel = (value: string) => OPERATION_ACTIONS[value] ? t(OPERATION_ACTIONS[value]) : value
async function loadOperations() { operationLoading.value = true; operationQuery.date_from = operationRange.value?.[0]; operationQuery.date_to = operationRange.value?.[1]; try { const result = await getOperationLogs(operationQuery); operationItems.value = result.items; operationTotal.value = result.total } catch (e) { ElMessage.error(getRequestErrorMessage(e, 'logs.operationLoadFailed')) } finally { operationLoading.value = false } }
async function loadPublishes() { publishLoading.value = true; publishQuery.date_from = publishRange.value?.[0]; publishQuery.date_to = publishRange.value?.[1]; try { const result = await getPublishLogs(publishQuery); publishItems.value = result.items; publishTotal.value = result.total } catch (e) { ElMessage.error(getRequestErrorMessage(e, 'logs.publishLoadFailed')) } finally { publishLoading.value = false } }
function resetOperations() { Object.assign(operationQuery, { page: 1, action: '', user_id: undefined }); operationRange.value = undefined; loadOperations() }
function resetPublishes() { Object.assign(publishQuery, { page: 1, keyword: '', content_type: '', status: '' }); publishRange.value = undefined; loadPublishes() }
onMounted(() => { loadOperations(); loadPublishes() })
</script>
<template>
  <div class="page-shell">
    <PageHeader :title="t('nav.logs')" :description="t('logs.description')" :eyebrow="t('kicker.auditDeliveryLog')" />
    <section class="paper-card log-card"><el-tabs v-model="activeTab">
      <el-tab-pane :label="t('logs.operation')" name="operations"><div class="tab-description"><div><strong>{{ t('logs.operation') }}</strong><span>{{ t('logs.operationDescription') }}</span></div></div><div class="tab-filter"><el-select v-model="operationQuery.action" clearable :placeholder="t('logs.allOperationTypes')" style="width:180px"><el-option v-for="action in actions" :key="action.value" :label="action.label" :value="action.value" /></el-select><el-date-picker v-model="operationRange" type="daterange" value-format="YYYY-MM-DD" :start-placeholder="t('common.startDate')" :end-placeholder="t('common.endDate')" /><el-button type="primary" :icon="Search" @click="operationQuery.page = 1; loadOperations()">{{ t('common.query') }}</el-button><el-button :icon="RefreshRight" @click="resetOperations">{{ t('common.reset') }}</el-button></div><el-table v-loading="operationLoading" :data="operationItems"><el-table-column :label="t('common.time')" width="170"><template #default="scope">{{ formatDate(scope.row.created_at) }}</template></el-table-column><el-table-column prop="user_name" :label="t('logs.user')" width="130" /><el-table-column prop="action" :label="t('logs.action')" width="150"><template #default="scope"><el-tag effect="plain" type="info">{{ operationLabel(scope.row.action) }}</el-tag></template></el-table-column><el-table-column prop="object" :label="t('logs.object')" min-width="150" /><el-table-column prop="description" :label="t('logs.details')" min-width="260" /></el-table><div class="pagination-wrap"><el-pagination v-model:current-page="operationQuery.page" v-model:page-size="operationQuery.page_size" :total="operationTotal" layout="total, sizes, prev, pager, next" @change="loadOperations" /></div></el-tab-pane>
      <el-tab-pane :label="t('logs.publish')" name="publishes"><div class="tab-description"><div><strong>{{ t('logs.publish') }}</strong><span>{{ t('logs.publishDescription') }}</span></div></div><div class="tab-filter"><el-input v-model="publishQuery.keyword" clearable :placeholder="t('content.title')" style="width:190px" /><el-select v-model="publishQuery.content_type" clearable :placeholder="t('common.allContentTypes')" style="width:155px"><el-option v-for="(label, value) in CONTENT_TYPES" :key="value" :label="t(label)" :value="value as ContentType" /></el-select><el-select v-model="publishQuery.status" clearable :placeholder="t('common.allStatuses')" style="width:130px"><el-option v-for="[value, label] in publishLogStatuses" :key="value" :label="t(label)" :value="value as PublishRecordStatus" /></el-select><el-date-picker v-model="publishRange" type="daterange" value-format="YYYY-MM-DD" :start-placeholder="t('common.startDate')" :end-placeholder="t('common.endDate')" /><el-button type="primary" :icon="Search" @click="publishQuery.page = 1; loadPublishes()">{{ t('common.query') }}</el-button><el-button :icon="RefreshRight" @click="resetPublishes">{{ t('common.reset') }}</el-button></div><el-table v-loading="publishLoading" :data="publishItems"><el-table-column :label="t('common.time')" width="165"><template #default="scope">{{ formatDate(scope.row.created_at) }}</template></el-table-column><el-table-column prop="content_title" :label="t('logs.content')" min-width="190" /><el-table-column prop="target_name" :label="t('content.publishTarget')" width="130" /><el-table-column :label="t('logs.publishResult')" width="100"><template #default="scope"><ContentStatus kind="publish-record" :status="scope.row.status" /></template></el-table-column><el-table-column :label="t('publishTarget.accessUrl')" min-width="220"><template #default="scope"><a v-if="scope.row.view_url" :href="scope.row.view_url" target="_blank" rel="noopener noreferrer" class="log-url mono">{{ scope.row.view_url }}</a><span v-else>—</span></template></el-table-column><el-table-column :label="t('logs.failureReason')" min-width="200"><template #default="scope"><el-tooltip v-if="scope.row.failure_reason" :content="scope.row.failure_reason" placement="top"><span class="failure-reason">{{ scope.row.failure_reason }}</span></el-tooltip><span v-else>—</span></template></el-table-column></el-table><div class="pagination-wrap"><el-pagination v-model:current-page="publishQuery.page" v-model:page-size="publishQuery.page_size" :total="publishTotal" layout="total, sizes, prev, pager, next" @change="loadPublishes" /></div></el-tab-pane>
    </el-tabs></section>
  </div>
</template>
<style scoped>
.log-card { padding: 4px 20px 18px; }.log-card :deep(.el-tabs__header) { margin-bottom: 0; }.tab-description { min-height: 70px; display: flex; align-items: center; justify-content: space-between; }.tab-description div { display: flex; flex-direction: column; gap: 5px; }.tab-description strong { font-size: 14px; }.tab-description span { color: #8c95a4; font-size: 11px; }.tab-filter { display: flex; gap: 9px; padding: 13px 14px; margin-bottom: 14px; background: #f7f8fa; border: 1px solid #e6e9ee; }.log-url { display: block; overflow: hidden; color: var(--blue); font-size: 10px; text-overflow: ellipsis; white-space: nowrap; }.failure-reason { display: block; max-width: 230px; overflow: hidden; color: var(--danger); text-overflow: ellipsis; white-space: nowrap; }
</style>
