<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { ArrowLeft, Check, Close } from '@element-plus/icons-vue'
import PageHeader from '@/components/PageHeader.vue'
import ContentPreview from '@/components/ContentPreview.vue'
import PublishFlow from '@/components/PublishFlow.vue'
import { approveReview, getReviewDetail, rejectReview } from '@/api/reviews'
import { getContentPreview } from '@/api/contents'
import { getRequestErrorMessage } from '@/api/request'
import { CONTENT_TYPES, PUBLISH_TARGET_TYPES } from '@/constants'
import { formatDate, formatFileSize } from '@/utils/format'
import type { PreviewData } from '@/types/content'
import type { PublishTarget } from '@/types/publish'
import type { ReviewDetail } from '@/types/review'

const route = useRoute(); const router = useRouter(); const id = Number(route.params.contentId); const loading = ref(true); const actionLoading = ref(false); const detail = ref<ReviewDetail>(); const preview = ref<PreviewData>(); const rejectVisible = ref(false); const rejectFormRef = ref<FormInstance>(); const rejectForm = reactive({ comment: '' })
const { t } = useI18n()
const rejectRules = computed<FormRules>(() => ({ comment: [{ required: true, message: t('validation.rejectReasonRequired'), trigger: 'blur' }, { min: 5, message: t('validation.rejectReasonMin'), trigger: 'blur' }] }))
function targetLocation(target?: PublishTarget | null) { if (!target) return '—'; if (target.target_type === 'local') return target.publish_root || '—'; if (target.target_type === 'sftp') return `${target.config?.host || '—'}:${target.config?.port || 22}${target.config?.remote_root || ''}`; if (target.target_type === 'github' || target.target_type === 'github_pages') return `${target.config?.owner || '—'}/${target.config?.repo || '—'} @ ${target.config?.branch || '—'} / ${target.config?.repo_path || ''}`; if (target.target_type === 'onedrive') return `Drive ${target.config?.drive_id || '—'} / ${target.config?.folder_path || ''}`; if (target.target_type === 'instagram') return `Instagram ${target.config?.ig_user_id || '—'}`; return String(target.config?.folder_path || '—') }
function targetUrl(target?: PublishTarget | null) { if (target?.target_type === 'instagram') return String(target.config?.media_base_url || '—'); return target?.base_url || String(target?.config?.base_url || '—') }
async function load() { loading.value = true; try { const [result, previewResult] = await Promise.all([getReviewDetail(id), getContentPreview(id)]); detail.value = result; preview.value = previewResult } catch (e) { ElMessage.error(getRequestErrorMessage(e, 'review.detailLoadFailed')) } finally { loading.value = false } }
async function approve() { try { await ElMessageBox.confirm(t('review.approveConfirm'), t('review.approvePublish'), { type: 'warning', confirmButtonText: t('review.approvePublish'), cancelButtonText: t('common.cancel') }); actionLoading.value = true; await approveReview(id, '内容与发布目标确认无误'); ElMessage.success(t('review.approveSucceeded')); await router.push({ path: `/contents/${id}`, query: { publishing: '1' } }) } catch (e) { if (e instanceof Error) ElMessage.error(getRequestErrorMessage(e)) } finally { actionLoading.value = false } }
async function reject() { if (!await rejectFormRef.value?.validate().catch(() => false)) return; actionLoading.value = true; try { await rejectReview(id, rejectForm.comment); ElMessage.success(t('review.rejectSucceeded')); rejectVisible.value = false; await load() } catch (e) { ElMessage.error(getRequestErrorMessage(e, 'review.rejectFailed')) } finally { actionLoading.value = false } }
onMounted(load)
</script>
<template>
  <div class="page-shell" v-loading="loading">
    <PageHeader :title="detail?.content.title || t('review.detail')" :description="t('review.detailDescription')" :eyebrow="t('kicker.reviewInspection')"><template #actions><el-button :icon="ArrowLeft" @click="router.push('/reviews')">{{ t('review.backQueue') }}</el-button><template v-if="detail?.content.review_status === 'pending'"><el-button type="danger" plain :icon="Close" @click="rejectVisible = true">{{ t('review.reject') }}</el-button><el-button type="primary" :icon="Check" :loading="actionLoading" @click="approve">{{ t('review.approvePublish') }}</el-button></template></template></PageHeader>
    <PublishFlow v-if="detail" :content="detail.content" />
    <el-alert v-if="detail?.content.publish_status === 'failed'" :title="t('review.publishFailedTitle')" :description="detail.content.failure_reason" type="error" :closable="false" show-icon />
    <div v-if="detail" class="review-grid">
      <div class="stack-12">
        <section class="paper-card review-section"><div class="section-head"><span class="section-kicker">{{ t('kicker.contentCheck') }}</span><h2>{{ t('review.contentAndFiles') }}</h2></div><el-descriptions :column="2" border><el-descriptions-item :label="t('content.contentType')">{{ t(CONTENT_TYPES[detail.content.content_type]) }}</el-descriptions-item><el-descriptions-item :label="t('content.category')">{{ detail.content.category }}</el-descriptions-item><el-descriptions-item :label="t('content.creator')">{{ detail.content.creator_name }}</el-descriptions-item><el-descriptions-item :label="t('content.submittedAt')">{{ formatDate(detail.content.submitted_at) }}</el-descriptions-item><el-descriptions-item :label="t('content.originalFile')" :span="2">{{ detail.content.source_is_directory || (detail.content.files?.length || 0) > 1 ? t('content.filesAndFolders', { count: detail.content.files?.length || 0 }) : detail.content.file_name || detail.content.files?.[0]?.name || t('content.pageContent') }} <span class="muted">{{ detail.content.file_size ? `· ${formatFileSize(detail.content.file_size)}` : '' }}</span></el-descriptions-item></el-descriptions><div class="description-block"><span>{{ t('content.description') }}</span><p>{{ detail.content.description || t('content.noDescriptionEntered') }}</p></div></section>
        <section class="paper-card review-section"><div class="section-head"><span class="section-kicker">{{ t('kicker.preview') }}</span><h2>{{ t('content.preview') }}</h2></div><ContentPreview :content-id="id" :preview="preview" /></section>
      </div>
      <aside class="stack-12">
        <section class="paper-card review-section target-card"><div class="section-head"><span class="section-kicker">{{ t('kicker.destination') }}</span><h2>{{ t('review.targetVerification') }}</h2></div><dl><div><dt>{{ t('publishTarget.name') }}</dt><dd>{{ detail.publish_target?.name }}</dd></div><div><dt>{{ t('publishTarget.targetType') }}</dt><dd>{{ detail.publish_target ? t(PUBLISH_TARGET_TYPES[detail.publish_target.target_type]) : '—' }}</dd></div><div><dt>{{ t('publishTarget.supportedTypes') }}</dt><dd>{{ detail.publish_target?.content_types.map(item => t(CONTENT_TYPES[item])).join(t('common.listSeparator')) }}</dd></div><div><dt>{{ t('publishTarget.location') }}</dt><dd class="mono path">{{ targetLocation(detail.publish_target) }}</dd></div><div><dt>{{ t('publishTarget.accessUrl') }}</dt><dd class="mono path">{{ targetUrl(detail.publish_target) }}</dd></div><div v-if="detail.publish_target?.credential_ref"><dt>{{ t('publishTarget.credentialRef') }}</dt><dd class="mono path">{{ detail.publish_target.credential_ref }}</dd></div><div><dt>{{ t('common.currentStatus') }}</dt><dd><el-tag :type="detail.publish_target?.enabled ? 'success' : 'danger'">{{ t(detail.publish_target?.enabled ? 'common.enabled' : 'common.disabled') }}</el-tag></dd></div></dl></section>
        <section class="paper-card review-section"><div class="section-head"><span class="section-kicker">{{ t('kicker.auditTrail') }}</span><h2>{{ t('review.history') }}</h2></div><el-timeline><el-timeline-item v-for="record in detail.history" :key="record.id" :timestamp="formatDate(record.created_at)" placement="top" :type="record.action === 'approve' ? 'success' : record.action === 'reject' ? 'danger' : 'primary'"><strong>{{ record.operator_name }}</strong><p>{{ record.comment }}</p></el-timeline-item></el-timeline></section>
      </aside>
    </div>
    <el-dialog v-model="rejectVisible" :title="t('review.rejectDialogTitle')" width="500px"><el-alert :title="t('review.rejectHint')" type="warning" :closable="false" show-icon /><el-form ref="rejectFormRef" :model="rejectForm" :rules="rejectRules" label-position="top" style="margin-top:18px"><el-form-item :label="t('review.rejectReason')" prop="comment"><el-input v-model="rejectForm.comment" type="textarea" :rows="5" maxlength="300" show-word-limit :placeholder="t('review.rejectPlaceholder')" /></el-form-item></el-form><template #footer><el-button @click="rejectVisible = false">{{ t('common.cancel') }}</el-button><el-button type="danger" :loading="actionLoading" @click="reject">{{ t('review.confirmReject') }}</el-button></template></el-dialog>
  </div>
</template>
<style scoped>
.review-grid { display: grid; grid-template-columns: minmax(0, 1.6fr) minmax(320px, .75fr); gap: 14px; align-items: start; }.review-section { padding: 0 20px 20px; }.section-head { min-height: 66px; display: flex; flex-direction: column; justify-content: center; margin-bottom: 18px; border-bottom: 1px solid var(--line); }.section-head h2 { margin: 4px 0 0; font-size: 16px; }.description-block { margin-top: 18px; padding: 14px 16px; background: #f7f8fa; }.description-block span { color: #7b8494; font-size: 11px; }.description-block p { margin: 6px 0 0; font-size: 13px; line-height: 1.7; }.target-card { border-top: 3px solid var(--accent); }.target-card dl { margin: 0; }.target-card dl div { padding: 10px 0; border-bottom: 1px solid #edf0f3; }.target-card dl div:last-child { border: 0; }.target-card dt { margin-bottom: 5px; color: #8891a0; font-size: 11px; }.target-card dd { margin: 0; font-size: 12px; font-weight: 550; }.target-card .path { overflow-wrap: anywhere; color: #4a5c77; font-size: 10px; font-weight: 400; }.el-timeline { padding-left: 5px; }.el-timeline p { margin: 4px 0 0; color: #697487; font-size: 12px; line-height: 1.6; }
</style>
