<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { Plus, RefreshRight, Search } from '@element-plus/icons-vue'
import PageHeader from '@/components/PageHeader.vue'
import { getDepartments } from '@/api/departments'
import { createUser, deleteUser, getUsers, updateUser, updateUserStatus } from '@/api/users'
import { getRequestErrorMessage } from '@/api/request'
import { USER_ROLES, USER_STATUS } from '@/constants'
import { formatDate } from '@/utils/format'
import type { User, UserPayload, UserQuery, UserRole, UserStatus } from '@/types/user'
import type { Department } from '@/types/department'

const loading = ref(false); const saving = ref(false); const items = ref<User[]>([]); const total = ref(0); const dialogVisible = ref(false); const editingId = ref<number>(); const formRef = ref<FormInstance>()
const { t } = useI18n()
const departments = ref<Department[]>([])
const query = reactive<UserQuery>({ page: 1, page_size: 10, keyword: '', role: '', status: '' })
const form = reactive<UserPayload>({ username: '', name: '', department: '', password: '', role: 'employee', status: 'active' })
const roleLabel = (value: UserRole) => t(USER_ROLES[value])
const statusLabel = (value: UserStatus) => t(USER_STATUS[value])
const rules = computed<FormRules>(() => ({ username: [{ required: true, message: t('validation.usernameRequired'), trigger: 'blur' }], name: [{ required: true, message: t('validation.nameRequired'), trigger: 'blur' }], department: [{ required: true, message: t('validation.departmentRequired'), trigger: 'change' }], password: [{ validator: (_rule, value, callback) => { if (!editingId.value && !value) callback(new Error(t('validation.newUserPasswordRequired'))); else if (value && value.length < 6) callback(new Error(t('validation.passwordMin'))); else callback() }, trigger: 'blur' }], role: [{ required: true, message: t('validation.roleRequired'), trigger: 'change' }] }))
async function load() { loading.value = true; try { const result = await getUsers(query); items.value = result.items; total.value = result.total } catch (e) { ElMessage.error(getRequestErrorMessage(e, 'user.listLoadFailed')) } finally { loading.value = false } }
async function loadDepartments() { try { departments.value = await getDepartments(true) } catch (e) { ElMessage.error(getRequestErrorMessage(e, 'department.listLoadFailed')) } }
function reset() { Object.assign(query, { page: 1, keyword: '', role: '', status: '' }); load() }
function openCreate() { editingId.value = undefined; Object.assign(form, { username: '', name: '', department: '', password: '', role: 'employee', status: 'active' }); dialogVisible.value = true }
function openEdit(user: User) { editingId.value = user.id; Object.assign(form, { username: user.username, name: user.name, department: user.department || '', password: '', role: user.role, status: user.status }); dialogVisible.value = true }
async function save() { if (!await formRef.value?.validate().catch(() => false)) return; saving.value = true; try { if (editingId.value) await updateUser(editingId.value, form); else await createUser(form); ElMessage.success(t(editingId.value ? 'user.updated' : 'user.created')); dialogVisible.value = false; load() } catch (e) { ElMessage.error(getRequestErrorMessage(e, 'common.saveFailed')) } finally { saving.value = false } }
async function changeStatus(user: User) { const next: UserStatus = user.status === 'active' ? 'disabled' : 'active'; try { if (next === 'disabled') await ElMessageBox.confirm(t('user.disableConfirm', { name: user.name }), t('user.disableTitle'), { type: 'warning', confirmButtonText: t('common.disable'), cancelButtonText: t('common.cancel') }); await updateUserStatus(user.id, next); ElMessage.success(t(next === 'active' ? 'user.enabled' : 'user.disabled')); load() } catch (e) { if (e instanceof Error) ElMessage.error(getRequestErrorMessage(e)) } }
async function remove(user: User) { try { await ElMessageBox.confirm(t('user.deleteConfirm', { name: user.name }), t('user.deleteTitle'), { type: 'warning', confirmButtonText: t('common.delete'), cancelButtonText: t('common.cancel') }); await deleteUser(user.id); ElMessage.success(t('user.deleted')); load() } catch (e) { if (e instanceof Error) ElMessage.error(getRequestErrorMessage(e)) } }
onMounted(() => { load(); loadDepartments() })
</script>
<template>
  <div class="page-shell">
    <PageHeader :title="t('nav.users')" :description="t('user.description')" :eyebrow="t('kicker.accessDirectory')"><template #actions><el-button type="primary" :icon="Plus" @click="openCreate">{{ t('user.create') }}</el-button></template></PageHeader>
    <section class="paper-card filter-panel"><el-form inline><el-form-item :label="t('common.keyword')"><el-input v-model="query.keyword" clearable :placeholder="t('user.keywordPlaceholder')" /></el-form-item><el-form-item :label="t('user.role')"><el-select v-model="query.role" clearable :placeholder="t('user.allRoles')" style="width:140px"><el-option v-for="(label, value) in USER_ROLES" :key="value" :label="t(label)" :value="value as UserRole" /></el-select></el-form-item><el-form-item :label="t('common.status')"><el-select v-model="query.status" clearable :placeholder="t('common.allStatuses')" style="width:120px"><el-option v-for="(label, value) in USER_STATUS" :key="value" :label="t(label)" :value="value as UserStatus" /></el-select></el-form-item><el-form-item><el-button type="primary" :icon="Search" @click="query.page = 1; load()">{{ t('common.query') }}</el-button><el-button :icon="RefreshRight" @click="reset">{{ t('common.reset') }}</el-button></el-form-item></el-form></section>
    <section class="paper-card table-panel"><div class="table-toolbar"><span class="table-count">{{ t('user.totalCount', { count: total }) }}</span><span class="permission-note">{{ t('user.departmentPermissionHint') }}</span></div><el-table v-loading="loading" :data="items"><el-table-column prop="username" :label="t('user.username')" min-width="140"><template #default="scope"><span class="mono username">{{ scope.row.username }}</span></template></el-table-column><el-table-column prop="name" :label="t('user.name')" min-width="120" /><el-table-column prop="department" :label="t('user.department')" min-width="130"><template #default="scope">{{ scope.row.department || t('common.unset') }}</template></el-table-column><el-table-column :label="t('user.role')" width="120"><template #default="scope"><el-tag :type="scope.row.role === 'admin' ? 'warning' : 'info'">{{ roleLabel(scope.row.role) }}</el-tag></template></el-table-column><el-table-column :label="t('common.status')" width="110"><template #default="scope"><span class="status-dot" :class="scope.row.status" />{{ statusLabel(scope.row.status) }}</template></el-table-column><el-table-column :label="t('common.createdAt')" min-width="170"><template #default="scope">{{ formatDate(scope.row.created_at) }}</template></el-table-column><el-table-column :label="t('common.actions')" width="210" fixed="right"><template #default="scope"><el-button link type="primary" @click="openEdit(scope.row)">{{ t('common.edit') }}</el-button><el-button link :type="scope.row.status === 'active' ? 'warning' : 'success'" @click="changeStatus(scope.row)">{{ t(scope.row.status === 'active' ? 'common.disable' : 'common.enable') }}</el-button><el-button link type="danger" @click="remove(scope.row)">{{ t('common.delete') }}</el-button></template></el-table-column></el-table><div class="pagination-wrap"><el-pagination v-model:current-page="query.page" v-model:page-size="query.page_size" :total="total" layout="total, sizes, prev, pager, next" @change="load" /></div></section>
    <el-dialog v-model="dialogVisible" :title="t(editingId ? 'user.edit' : 'user.create')" width="520px" @closed="formRef?.clearValidate()"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="dialog-grid"><el-form-item :label="t('user.username')" prop="username"><el-input v-model="form.username" :disabled="Boolean(editingId)" :placeholder="t('user.usernamePlaceholder')" /></el-form-item><el-form-item :label="t('user.name')" prop="name"><el-input v-model="form.name" :placeholder="t('user.namePlaceholder')" /></el-form-item></div><el-form-item :label="t('user.department')" prop="department"><el-select v-model="form.department" filterable :placeholder="t('user.departmentPlaceholder')"><el-option v-for="item in departments" :key="item.id" :label="item.enabled ? item.name : t('common.disabledName', { name: item.name })" :value="item.name" :disabled="!item.enabled" /></el-select></el-form-item><el-form-item :label="t(editingId ? 'user.passwordOptional' : 'login.password')" prop="password"><el-input v-model="form.password" type="password" show-password :placeholder="t('user.passwordPlaceholder')" /></el-form-item><div class="dialog-grid"><el-form-item :label="t('user.role')" prop="role"><el-select v-model="form.role"><el-option v-for="(label, value) in USER_ROLES" :key="value" :label="t(label)" :value="value as UserRole" /></el-select></el-form-item><el-form-item :label="t('common.status')"><el-radio-group v-model="form.status"><el-radio value="active">{{ t('common.enable') }}</el-radio><el-radio value="disabled">{{ t('common.disable') }}</el-radio></el-radio-group></el-form-item></div></el-form><template #footer><el-button @click="dialogVisible = false">{{ t('common.cancel') }}</el-button><el-button type="primary" :loading="saving" @click="save">{{ t('common.save') }}</el-button></template></el-dialog>
  </div>
</template>
<style scoped>
.filter-panel :deep(.el-form-item) { margin-bottom: 12px; }.permission-note { color: #8c95a4; font-size: 11px; }.username { color: #3d5677; font-size: 12px; }.status-dot { display: inline-block; width: 7px; height: 7px; margin-right: 7px; border-radius: 50%; background: #a5adba; }.status-dot.active { background: #369071; box-shadow: 0 0 0 3px #e5f3ee; }.dialog-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }.dialog-grid .el-select { width: 100%; }
</style>
