<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox, type FormInstance, type FormRules } from 'element-plus'
import { Plus, RefreshRight, Search } from '@element-plus/icons-vue'
import PageHeader from '@/components/PageHeader.vue'
import { getDepartments } from '@/api/departments'
import { createUser, deleteUser, getUsers, updateUser, updateUserStatus } from '@/api/users'
import { USER_ROLES, USER_STATUS } from '@/constants'
import { formatDate } from '@/utils/format'
import type { User, UserPayload, UserQuery, UserRole, UserStatus } from '@/types/user'
import type { Department } from '@/types/department'

const loading = ref(false); const saving = ref(false); const items = ref<User[]>([]); const total = ref(0); const dialogVisible = ref(false); const editingId = ref<number>(); const formRef = ref<FormInstance>()
const departments = ref<Department[]>([])
const query = reactive<UserQuery>({ page: 1, page_size: 10, keyword: '', role: '', status: '' })
const form = reactive<UserPayload>({ username: '', name: '', department: '', password: '', role: 'employee', status: 'active' })
const roleLabel = (value: UserRole) => USER_ROLES[value]
const statusLabel = (value: UserStatus) => USER_STATUS[value]
const rules: FormRules = { username: [{ required: true, message: '请输入用户名', trigger: 'blur' }], name: [{ required: true, message: '请输入姓名', trigger: 'blur' }], department: [{ required: true, message: '请选择所属部门', trigger: 'change' }], password: [{ validator: (_rule, value, callback) => { if (!editingId.value && !value) callback(new Error('新增用户必须设置密码')); else if (value && value.length < 6) callback(new Error('密码至少 6 位')); else callback() }, trigger: 'blur' }], role: [{ required: true, message: '请选择角色', trigger: 'change' }] }
async function load() { loading.value = true; try { const result = await getUsers(query); items.value = result.items; total.value = result.total } catch (e) { ElMessage.error(e instanceof Error ? e.message : '用户列表加载失败') } finally { loading.value = false } }
async function loadDepartments() { try { departments.value = await getDepartments(true) } catch (e) { ElMessage.error(e instanceof Error ? e.message : '部门列表加载失败') } }
function reset() { Object.assign(query, { page: 1, keyword: '', role: '', status: '' }); load() }
function openCreate() { editingId.value = undefined; Object.assign(form, { username: '', name: '', department: '', password: '', role: 'employee', status: 'active' }); dialogVisible.value = true }
function openEdit(user: User) { editingId.value = user.id; Object.assign(form, { username: user.username, name: user.name, department: user.department || '', password: '', role: user.role, status: user.status }); dialogVisible.value = true }
async function save() { if (!await formRef.value?.validate().catch(() => false)) return; saving.value = true; try { if (editingId.value) await updateUser(editingId.value, form); else await createUser(form); ElMessage.success(editingId.value ? '用户信息已更新' : '用户已创建'); dialogVisible.value = false; load() } catch (e) { ElMessage.error(e instanceof Error ? e.message : '保存失败') } finally { saving.value = false } }
async function changeStatus(user: User) { const next: UserStatus = user.status === 'active' ? 'disabled' : 'active'; try { if (next === 'disabled') await ElMessageBox.confirm(`禁用后“${user.name}”将无法登录，确认继续吗？`, '禁用用户', { type: 'warning', confirmButtonText: '禁用', cancelButtonText: '取消' }); await updateUserStatus(user.id, next); ElMessage.success(next === 'active' ? '用户已启用' : '用户已禁用'); load() } catch (e) { if (e instanceof Error) ElMessage.error(e.message) } }
async function remove(user: User) { try { await ElMessageBox.confirm(`确认删除用户“${user.name}”吗？已有业务记录的用户将无法删除。`, '删除用户', { type: 'warning', confirmButtonText: '删除', cancelButtonText: '取消' }); await deleteUser(user.id); ElMessage.success('用户已删除'); load() } catch (e) { if (e instanceof Error) ElMessage.error(e.message) } }
onMounted(() => { load(); loadDepartments() })
</script>
<template>
  <div class="page-shell">
    <PageHeader title="用户管理" description="维护内部账号、所属部门、角色与启用状态。" eyebrow="ACCESS DIRECTORY"><template #actions><el-button type="primary" :icon="Plus" @click="openCreate">新增用户</el-button></template></PageHeader>
    <section class="paper-card filter-panel"><el-form inline><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="用户名、姓名或部门" /></el-form-item><el-form-item label="角色"><el-select v-model="query.role" clearable placeholder="全部角色" style="width:140px"><el-option v-for="(label, value) in USER_ROLES" :key="value" :label="label" :value="value as UserRole" /></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态" style="width:120px"><el-option v-for="(label, value) in USER_STATUS" :key="value" :label="label" :value="value as UserStatus" /></el-select></el-form-item><el-form-item><el-button type="primary" :icon="Search" @click="query.page = 1; load()">查询</el-button><el-button :icon="RefreshRight" @click="reset">重置</el-button></el-form-item></el-form></section>
    <section class="paper-card table-panel"><div class="table-toolbar"><span class="table-count">共 {{ total }} 个内部账号</span><span class="permission-note">内容权限可按所属部门控制</span></div><el-table v-loading="loading" :data="items"><el-table-column prop="username" label="用户名" min-width="140"><template #default="scope"><span class="mono username">{{ scope.row.username }}</span></template></el-table-column><el-table-column prop="name" label="姓名" min-width="120" /><el-table-column prop="department" label="所属部门" min-width="130"><template #default="scope">{{ scope.row.department || '未设置' }}</template></el-table-column><el-table-column label="角色" width="120"><template #default="scope"><el-tag :type="scope.row.role === 'admin' ? 'warning' : 'info'">{{ roleLabel(scope.row.role) }}</el-tag></template></el-table-column><el-table-column label="状态" width="110"><template #default="scope"><span class="status-dot" :class="scope.row.status" />{{ statusLabel(scope.row.status) }}</template></el-table-column><el-table-column label="创建时间" min-width="170"><template #default="scope">{{ formatDate(scope.row.created_at) }}</template></el-table-column><el-table-column label="操作" width="210" fixed="right"><template #default="scope"><el-button link type="primary" @click="openEdit(scope.row)">编辑</el-button><el-button link :type="scope.row.status === 'active' ? 'warning' : 'success'" @click="changeStatus(scope.row)">{{ scope.row.status === 'active' ? '禁用' : '启用' }}</el-button><el-button link type="danger" @click="remove(scope.row)">删除</el-button></template></el-table-column></el-table><div class="pagination-wrap"><el-pagination v-model:current-page="query.page" v-model:page-size="query.page_size" :total="total" layout="total, sizes, prev, pager, next" @change="load" /></div></section>
    <el-dialog v-model="dialogVisible" :title="editingId ? '编辑用户' : '新增用户'" width="520px" @closed="formRef?.clearValidate()"><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><div class="dialog-grid"><el-form-item label="用户名" prop="username"><el-input v-model="form.username" :disabled="Boolean(editingId)" placeholder="用于登录的唯一账号" /></el-form-item><el-form-item label="姓名" prop="name"><el-input v-model="form.name" placeholder="员工姓名" /></el-form-item></div><el-form-item label="所属部门" prop="department"><el-select v-model="form.department" filterable placeholder="请选择所属部门"><el-option v-for="item in departments" :key="item.id" :label="item.enabled ? item.name : `${item.name}（已禁用）`" :value="item.name" :disabled="!item.enabled" /></el-select></el-form-item><el-form-item :label="editingId ? '密码（留空表示不修改）' : '密码'" prop="password"><el-input v-model="form.password" type="password" show-password placeholder="至少 6 位" /></el-form-item><div class="dialog-grid"><el-form-item label="角色" prop="role"><el-select v-model="form.role"><el-option v-for="(label, value) in USER_ROLES" :key="value" :label="label" :value="value as UserRole" /></el-select></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio value="active">启用</el-radio><el-radio value="disabled">禁用</el-radio></el-radio-group></el-form-item></div></el-form><template #footer><el-button @click="dialogVisible = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>
<style scoped>
.filter-panel :deep(.el-form-item) { margin-bottom: 12px; }.permission-note { color: #8c95a4; font-size: 11px; }.username { color: #3d5677; font-size: 12px; }.status-dot { display: inline-block; width: 7px; height: 7px; margin-right: 7px; border-radius: 50%; background: #a5adba; }.status-dot.active { background: #369071; box-shadow: 0 0 0 3px #e5f3ee; }.dialog-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; }.dialog-grid .el-select { width: 100%; }
</style>
